version: "3.7"

networks:
    touchdownclub:
        driver: bridge
        ipam:
            config:
                -   subnet: 10.0.0.0/24
                    gateway: 10.0.0.254

services:
    app:
        container_name: tdc_php
        image: touchdownclub:dev
        working_dir: /srv
        volumes:
            - ".:/srv"
        ports:
            - "5173:5173"
        networks:
            touchdownclub:
                ipv4_address: 10.0.0.1

    db:
        container_name: tdc_db
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_HOST: 10.0.0.2
            MYSQL_ROOT_PASSWORD: touchdownclub
            MYSQL_USER: touchdownclub
            MYSQL_PASSWORD: touchdownclub
            MYSQL_DATABASE: touchdownclub
        volumes:
            - "./.mysql_data:/var/lib/mysql"
        ports:
            - "5506:3306"
        networks:
            touchdownclub:
                ipv4_address: 10.0.0.2

    nginx:
        container_name: tdc_nginx
        image: nginx:stable
        ports:
            - "8000:80"
        working_dir: /srv
        volumes:
            - ".:/srv"
            - "./nginx.conf:/etc/nginx/conf.d/default.conf"
        networks:
            touchdownclub:
                ipv4_address: 10.0.0.3

    redis:
        container_name: tdc_redis
        image: 'redis:alpine'
        ports:
            - "6379:6379"
        volumes:
            - './.redis_data:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        networks:
            touchdownclub:
                ipv4_address: 10.0.0.4

    adminer:
        container_name: tdc_adminer
        image: adminer:4.8.1
        environment:
            ADMINER_DEFAULT_SERVER: db
        ports:
            - "5001:8080"
        networks:
            touchdownclub:
                ipv4_address: 10.0.0.101
